[package]
name = "jacobian"
version = "0.1.0"
authors = ["Kit Sczudlo <kit@kitscz.com>"]

[dependencies]
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
reqwest = "0.8.1"
chrono = "0.4.0"
clap = "2.28.0"

