[package]
name = "jacobian"
version = "0.1.0"
authors = ["Kit Sczudlo <kitscuzz@scuzzstuff.com>"]

[dependencies]
serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"
reqwest = "0.5"
chrono = "0.3"

